### ISSUE TITLE
Cannot create required material because shader is null

### ISSUE THREAD

**Issue by SashaBes** [keijiro/BibcamUrp#1]
Hello,
your project works perfectly, but when I try to recreate it in a new URP project in the same version of Unity and with the same dependencies, I get these errors in the Decoder Scene:

Cannot create required material because shader is null
UnityEngine.Rendering.CoreUtils:CreateEngineMaterial (UnityEngine.Shader)
Bibcam.BibcamBackgroundPassFeature:get_Material () (at Assets/Scripts/BibcamBackgroundPassFeature.cs:72)
Bibcam.BibcamBackgroundPassFeature:Create () (at Assets/Scripts/BibcamBackgroundPassFeature.cs:81)
UnityEngine.Rendering.Universal.ScriptableRendererFeature:OnValidate () (at Library/PackageCache/com.unity.render-pipelines.universal@12.1.1/Runtime/ScriptableRendererFeature.cs:46)

Do you know how to solve this problem?

**Comment by keijiro** [comment]
I think you're using the old code. There is no line 72 in BibcamBackgroundPassFeature.cs with the current version.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it if it still reproduces.
